# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 19:21
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import uuid
from moneyed import Money, RUB

from youtube_platform.service_permission import ServicePermission
from youtube_platform.models import Feature, Plain, FeatureParameter

FEATURES = {
    'smart_search': (10, 'Умный поиск', False, ServicePermission.base),

    'commentators': (5, 'Комментаторы видео', True, ServicePermission.base),
    'user_channels': (5, 'Каналы пользователей сетей', True, ServicePermission.base),
    'channel_dynamic': (10, 'Динамика канала', True, ServicePermission.base),

    'top3_among_users': (10, 'ТОП 3 видео среди пользователей', True, ServicePermission.standart),
    'top3_video': (10, 'ТОП 3 видео', True, ServicePermission.standart),
    'collaboration': (10, 'Коллаборация', True, ServicePermission.standart),
    'auditory_analyze': (10, 'Анализ аудитории', True, ServicePermission.standart),
    'popular_tags': (10, 'Популярные тэги', True, ServicePermission.standart),

    'channel_subscribers': (20, 'Подписчики канала', True, ServicePermission.premium),
    'foreign_ad_track': (30, 'Отслеживание рекламы', True, ServicePermission.premium),
    'broadcast_message': (50, 'Рассылка сообщений', True, ServicePermission.premium)
}

PARAMS = {
    'smart_search': [
        ('key_phase', 'Ключевая фраза'),
        ('subscribers_more_then', 'Подписчиков больше'),
        ('views_count', 'Количество просмотров'),
        ('likes_rate', 'Количество лайков'),
        ('duration', 'Продолжительность'),
        ('comments_more_then', 'Комментариев больше'),
        ('upload_earle_then', 'Загружено ранее'),
        ('exclude_approved_channels', 'Исключить подтверждёные'),
        ('cc_license', 'Common Creative лицензия')
    ],
    'commentators': [('video_link', 'Ссылка на видео')],
    'user_channels': [('links', 'Ссылки на аккаунты'), ('social', 'Социальная сеть')],
    'channel_dynamic': [('channel_link', 'Ссылка на канал')],
    'top3_among_users': [('links', 'Ссылки на каналы пользователей')],
    'top3_video': [],
    'collaboration': [],
    'auditory_analyze': [],
    'popular_tags': [],
    'channel_subscribers': [('channel_link', 'Ссылка на канал')],
    'foreign_ad_track': [('tags', 'Ключевые слова')],
    'broadcast_message': [('message', 'Текст сообщения'), ('recipients', 'Получатели')]
}


def create_features(apps, *args, **kwargs):
    for feature, (cost, title, in_menu, perm) in FEATURES.items():
        params = [
            FeatureParameter.objects.create(
                parameter_name=name, parameter_title=p_title
            ) for name, p_title in PARAMS[feature]
        ]
        f = Feature.objects.create(
            feature_name=feature, quota_cost=cost, feature_title=title,
            in_menu=in_menu, plain_required=Plain.get_by_permission(perm)
        )
        f.parameters = params

BASE_DESCR = """
Получение комментов
Умный поиск
Получени каналов из файла с ссылками на соц.сети
Динамика любого канала
"""

STANDART_DESCR = """
Получение тех,кто лайкнул видео
Больше фильтров в умном поиске
ТОП 3 из понравившихся
Нет ограничений в функции Динамика Канала
Коллаборация
Самые популярные теги
Аналитика аудитории
"""

PREMIUM = """
Получение подписчиков
Все фильтры в умном поиске!
Снятие ограничений с анализа аудитории
Перевод базы каналов в базу соц.сетей
Пробуждение неактивной аудитории пользователя
Вшитая реклама
Слежка за конкурентами
Подсчёт ROI
"""

PLATINUM = """
Рассылка сообщений
"""

PLAINS = [
    ('Базовый', BASE_DESCR, Money(500, RUB), 500, False, 'fa-home', 1),
    ('Стандарт', STANDART_DESCR, Money(700, RUB), 700, False, 'fa-rocket', 2),
    ('Премиум', PREMIUM, Money(900, RUB), 900, False, 'fa-diamond', 3),
    ('Платинум', PLATINUM, Money(1500, RUB), 1500, True, 'fa-diamond', 4)
]

def create_permissions(apps, *args, **kwargs):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')
    Plain = apps.get_model('youtube_platform', 'Plain') 

    for title, descr, price, ql, hidden, icon, permission_level in PLAINS:
        Plain.objects.create(
            title=title, description=descr, price=price, hidden=hidden,
            quota_limit=ql, fa_icon_name=icon,
            permission_level=permission_level
        )

    pcontent_type = ContentType.objects.get_for_model(Permission)
    base_perm = Permission.objects.create(
        codename=ServicePermission.base.value,
        name='Base plane',
        content_type=pcontent_type
    )
    std_perm = Permission.objects.create(
        codename=ServicePermission.standart.value,
        name='Standart plane',
        content_type=pcontent_type
    )
    prem_perm = Permission.objects.create(
        codename=ServicePermission.premium.value,
        name='Premium plane',
        content_type=pcontent_type
    )

    Group.objects.create(
        name='base'
    ).permissions.add(base_perm)
    Group.objects.create(
        name='standart'
    ).permissions.add(std_perm)
    Group.objects.create(
        name='premium'
    ).permissions.add(prem_perm)

def reverse_create_permissions(apps, *args, **kwargs): 
    Permission = apps.get_model('auth', 'Permission') 
    Group = apps.get_model('auth', 'Group') 

    Permission.objects.all().delete() 
    Group.objects.all().delete() 

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('activation_token', models.UUIDField(null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_at', models.DateTimeField()),
                ('quota_exes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=256)),
                ('quota_cost', models.IntegerField(default=0)),
                ('feature_title', models.CharField(max_length=256)),
                ('in_menu', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=256)),
                ('parameter_title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_used', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.TextField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='youtube_platform.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='MessageBroadcastTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.CharField(max_length=1000)),
                ('message', models.CharField(max_length=1000)),
                ('done', models.BooleanField()),
                ('success', models.BooleanField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('RUB', 'Russian Ruble'), ('USD', 'US Dollar')], default='RUB', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='RUB', max_digits=10)),
                ('hidden', models.BooleanField(default=False)),
                ('quota_limit', models.IntegerField(default=1000)),
                ('permission_level', models.IntegerField()),
                ('fa_icon_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_url', models.URLField()),
                ('channel_id', models.CharField(max_length=255)),
                ('account_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='youtube_platform.AccountType')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ROILink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('label', models.CharField(max_length=256)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('visits', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_platform.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='messagebroadcasttask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_platform.Profile'),
        ),
        migrations.AddField(
            model_name='featureusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_history', to='youtube_platform.Profile'),
        ),
        migrations.AddField(
            model_name='feature',
            name='parameters',
            field=models.ManyToManyField(related_name='feature', to='youtube_platform.FeatureParameter'),
        ),
        migrations.AddField(
            model_name='feature',
            name='plain_required',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_platform.Plain'),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='plain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_platform.Plain'),
        ),
        migrations.RunPython(create_permissions, reverse_code=reverse_create_permissions), 
        migrations.RunPython(create_features, reverse_code=lambda *args: None)
    ]
