# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='channel_url',
            field=models.URLField(null=True),
        ),
    ]
