# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_platform', '0003_auto_20170326_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='expiry_at',
            field=models.DateTimeField(),
        ),
    ]
