# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_platform', '0005_messagebroadcasttask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagebroadcasttask',
            name='user',
        ),
        migrations.AddField(
            model_name='messagebroadcasttask',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='youtube_platform.Profile'),
            preserve_default=False,
        ),
    ]
