# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_platform', '0007_messagebroadcasttask_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=256)),
                ('quota_cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_used', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.CharField(max_length=512)),
                ('feature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='youtube_platform.Feature')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operations_history', to='youtube_platform.Feature')),
            ],
        ),
        migrations.AddField(
            model_name='accounttype',
            name='quota_limit',
            field=models.IntegerField(default=0),
        ),
    ]
