# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_platform', '0008_auto_20170328_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='quota_exes',
            field=models.IntegerField(default=0),
        ),
    ]
