# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 22:18
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_platform', '0009_accounttype_quota_exes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('RUB', 'Russian Ruble'), ('USD', 'US Dollar')], default='RUB', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='RUB', max_digits=10)),
            ],
        ),
    ]
