# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_platform', '0011_plain_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='plain',
            name='quota_limit',
            field=models.IntegerField(default=1000),
        ),
    ]
