# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_platform', '0014_auto_20170330_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='plain_required',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='youtube_platform.Plain'),
            preserve_default=False,
        ),
    ]
