# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 01:41
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.migrations import RunPython


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_platform', '0015_auto_20170330_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='parameters',
            field=models.ManyToManyField(to='youtube_platform.FeatureParameter'),
        ),
    ]
