# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 02:11
from __future__ import unicode_literals

from django.db import migrations
from django.db.migrations import RunPython

from youtube_platform.models import Feature, Plain, FeatureParameter
from youtube_platform.service_permission import ServicePermission


FEATURES = {
    'smart_search': (10, 'Умный поиск', False, ServicePermission.base),

    'commentators': (5, 'Комментаторы видео', True, ServicePermission.base),
    'user_channels': (5, 'Каналы пользователей сетей', True, ServicePermission.base),
    'channel_dynamic': (10, 'Динамика канала', True, ServicePermission.base),

    'top3_among_users': (10, 'ТОП 3 видео среди пользователей', True, ServicePermission.standart),
    'top3_video': (10, 'ТОП 3 видео', True, ServicePermission.standart),
    'collaboration': (10, 'Коллаборация', True, ServicePermission.standart),
    'auditory_analyze': (10, 'Анализ аудитории', True, ServicePermission.standart),
    'popular_tags': (10, 'Популярные тэги', True, ServicePermission.standart),

    'channel_subscribers': (20, 'Подписчики канала', True, ServicePermission.premium),
    'foreign_ad_track': (30, 'Отслеживание рекламы', True, ServicePermission.premium),
    'broadcast_message': (50, 'Рассылка сообщений', True, ServicePermission.premium)
}

PARAMS = {
    'smart_search': [
        ('key_phase', 'Ключевая фраза'),
        ('subscribers_more_then', 'Подписчиков больше'),
        ('views_count', 'Количество просмотров'),
        ('likes_rate', 'Количество лайков'),
        ('duration', 'Продолжительность'),
        ('comments_more_then', 'Комментариев больше'),
        ('upload_earle_then', 'Загружено ранее'),
        ('exclude_approved_channels', 'Исключить подтверждёные'),
        ('cc_license', 'Common Creative лицензия')
    ],
    'commentators': [('video_link', 'Ссылка на видео')],
    'user_channels': [('links', 'Ссылки на аккаунты'), ('social', 'Социальная сеть')],
    'channel_dynamic': [('channel_link', 'Ссылка на канал')],
    'top3_among_users': [('links', 'Ссылки на каналы пользователей')],
    'top3_video': [],
    'collaboration': [],
    'auditory_analyze': [],
    'popular_tags': [],
    'channel_subscribers': [('channel_link', 'Ссылка на канал')],
    'foreign_ad_track': [('tags', 'Ключевые слова')],
    'broadcast_message': [('message', 'Текст сообщения'), ('recipients', 'Получатели')]
}


def create_features(apps, *args, **kwargs):
    for feature, (cost, title, in_menu, perm) in FEATURES.items():
        params = [
            FeatureParameter.objects.create(
                parameter_name=name, parameter_title=p_title
            ) for name, p_title in PARAMS[feature]
        ]
        f = Feature.objects.create(
            feature_name=feature, quota_cost=cost, feature_title=title,
            in_menu=in_menu, plain_required=Plain.get_by_permission(perm)
        )
        f.parameters = params


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_platform', '0016_auto_20170330_0141'),
    ]

    operations = [
        RunPython(create_features, reverse_code=lambda *args: None)
    ]
