# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_platform', '0017_auto_20170330_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='in_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='parameters',
            field=models.ManyToManyField(related_name='feature', to='youtube_platform.FeatureParameter'),
        ),
        migrations.AlterField(
            model_name='featureusage',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='youtube_platform.Feature'),
        ),
        migrations.AlterField(
            model_name='featureusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_history', to='youtube_platform.Profile'),
        ),
    ]
