# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_platform', '0018_auto_20170330_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureusage',
            name='parameters',
            field=models.TextField(),
        ),
    ]
