# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid

from django.db.migrations import RunPython

from youtube_platform.models import FeatureParameter, Feature, Plain
from youtube_platform.service_permission import ServicePermission


FEATURES = {
    'count_roi': (10, 'Подсчёт ROI', False, ServicePermission.premium)
}

PARAMS = {
    'count_roi': [('label', 'Название ссылки'), ('link', 'Ссылка')]
}


def create_features(apps, *args, **kwargs):
    for feature, (cost, title, in_menu, perm) in FEATURES.items():
        params = [
            FeatureParameter.objects.create(
                parameter_name=name, parameter_title=p_title
            ) for name, p_title in PARAMS[feature]
        ]
        f = Feature.objects.create(
            feature_name=feature, quota_cost=cost, feature_title=title,
            in_menu=in_menu, plain_required=Plain.get_by_permission(perm)
        )
        f.parameters = params


class Migration(migrations.Migration):
    dependencies = [
        ('youtube_platform', '0019_auto_20170330_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='ROILink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('label', models.CharField(max_length=256)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('visits', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_platform.Profile')),
            ],
        ),
        RunPython(create_features, lambda *args: None)
    ]
